using Noted.Models;

namespace Noted.Services;

public interface IAppSettingsService {
    string AppDataDirectory { get; }
    string? LoadNotesDirectory();
    void SaveNotesDirectory(string notesDirectory);
    IReadOnlyList<string> LoadPinnedNotes();
    void SavePinnedNotes(IReadOnlyList<string> pinnedNotes);
    bool LoadShowModifiedSubtitle();
    void SaveShowModifiedSubtitle(bool showModifiedSubtitle);
    NoteTimestampPlacement LoadTimestampPlacement();
    void SaveTimestampPlacement(NoteTimestampPlacement timestampPlacement);
    NewNoteMode LoadNewNoteMode();
    void SaveNewNoteMode(NewNoteMode newNoteMode);
    bool LoadPromptForNoteName();
    void SavePromptForNoteName(bool promptForNoteName);
    string? LoadCustomHeader();
    void SaveCustomHeader(string? customHeader);
    (string modifiers, string key) LoadNotesHotkey();
    void SaveNotesHotkey(string modifiers, string key);
    (string modifiers, string key) LoadChecklistHotkey();
    void SaveChecklistHotkey(string modifiers, string key);
    (string modifiers, string key) LoadDictionaryHotkey();
    void SaveDictionaryHotkey(string modifiers, string key);
    bool LoadGhostModeEnabled();
    void SaveGhostModeEnabled(bool enabled);
    double LoadGhostModeOpacity();
    void SaveGhostModeOpacity(double opacity);
    double LoadDefaultOpacity();
    void SaveDefaultOpacity(double opacity);
    AppThemeMode LoadAppThemeMode();
    void SaveAppThemeMode(AppThemeMode mode);
    string LoadAccentColor();
    void SaveAccentColor(string color);
    FolderNavigationMode LoadFolderNavigationMode();
    void SaveFolderNavigationMode(FolderNavigationMode mode);
    IReadOnlyList<ChecklistItemState>? LoadLegacyChecklistItems();
    void ClearLegacyChecklistItems();
    ChecklistWindowState LoadChecklistWindowState();
    void SaveChecklistWindowState(ChecklistWindowState state);
    IReadOnlyList<DictionaryItemState>? LoadLegacyDictionaryItems();
    void ClearLegacyDictionaryItems();
    DictionaryWindowState LoadDictionaryWindowState();
    void SaveDictionaryWindowState(DictionaryWindowState state);
    bool LoadMainHideButtonHidesAll();
    void SaveMainHideButtonHidesAll(bool hidesAll);
    bool LoadConfirmNoteDeletion();
    void SaveConfirmNoteDeletion(bool confirm);
    ScratchpadWindowState LoadScratchpadWindowState();
    void SaveScratchpadWindowState(ScratchpadWindowState state);
    NoteEditorWindowState LoadNoteEditorWindowState();
    void SaveNoteEditorWindowState(NoteEditorWindowState state);
    MiniPadWindowState LoadMiniPadWindowState();
    void SaveMiniPadWindowState(MiniPadWindowState state);
    bool LoadReopenEditorTabsOnStartup();
    void SaveReopenEditorTabsOnStartup(bool enabled);
    string? LoadPreferredDisplayDeviceName();
    void SavePreferredDisplayDeviceName(string? deviceName);
}
